---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/health_check":
    get:
      summary: Health Check
      tags:
      - Health Check
      responses:
        '200':
          description: status OK
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
